### ISSUE TITLE
Merge develop branch to master

### ISSUE THREAD

**Issue by mikz** [chenxianyu2015/liquid-lua#6]
@chenxianyu2015 thanks for awesome project.

https://github.com/chenxianyu2015/liquid-lua/commit/1fc3c17d84740f152ad73d3a12b03b7383d327fa has cool new interface. Would be great to merge it into master so it can be installed locally by #4 .

**Comment by chenxianyu2015** [comment]
@mikz  
Sorry to reply you so late. 
I will check them ASAP.
thanks a lot for your effort to improve this project.

**Comment by mikz** [comment]
No worries, we are using our fork for now. https://github.com/3scale/liquid-lua

BTW I pushed a luarocks pointing to our git: https://luarocks.org/modules/3scale/liquid and will point it to your repo once changes I need are in and give you ownership if you'd like of course.

And BTW I'm using this as a templating language for project generator for OpenResty applications including nginx configuration (for configuring directives like lua_code_cache). 

nginx config: https://github.com/3scale/apicast-cli/blob/master/src/apicast-cli/blank-app/nginx/main.conf.liquid
readme: https://github.com/3scale/apicast-cli/blob/master/src/apicast-cli/blank-app/README.md
